export const PLUS = "+";
export const DATA_DUMMY = [
  {
    id: 1,
    stor: "Store 1",
    bType: "Shope",
    branchs: 1,
    sDate: "OCT 11 2010",
    sStatus: "Active",
  },
  {
    id: 2,
    stor: "Store 2",
    bType: "Online",
    branchs: 4,
    sDate: "JAN 1 2015",
    sStatus: "Inactive",
  },
  {
    id: 3,
    stor: "Store 3",
    bType: "Shope",
    branchs: 2,
    sDate: "Nov 01 2016",
    sStatus: "Active",
  },
  {
    id: 4,
    stor: "Store 4",
    bType: "Online stor",
    branchs: 1,
    sDate: "SEP 1 2020",
    sStatus: "Active",
  },
  {
    id: 5,
    stor: "Store 5",
    bType: "Cart",
    branchs: 1,
    sDate: "AUG 2 2019",
    sStatus: "inActive",
  },
  {
    id: 6,
    stor: "Store 6",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
  {
    id: 7,
    stor: "Store 7",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
  {
    id: 8,
    stor: "Store 8",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
  {
    id: 9,
    stor: "Store 9",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
  {
    id: 10,
    stor: "Store 10",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
  {
    id: 11,
    stor: "Store 11",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
  {
    id: 12,
    stor: "Store 12",
    bType: "Shope",
    branchs: 1,
    sDate: "Nov 11 2010",
    sStatus: "Active",
  },
];
